mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from collection import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^$', views.home, name='home'),
	url(r'^climbs/(?P<slug>[-\w]+)/$', views.climb_detail, name='climb_detail'),
	url(r'^climbs/(?P<slug>[-\w]+)/edit/$', views.edit_climb, name='edit_climb'),
	url(r'^climbs/(?P<slug>[-\w]+)/videos/(?P<videoid>\d+)/$', views.video_delete, name='video_delete'),
	url(r'^climbs/(?P<slug>[-\w]+)/videos/(?P<videoid>\d+)/confirm/$', views.video_delete_confirm, name='video_delete_confirm'),
	url(r'^sends/(?P<sendid>\d+)/$', views.send_detail, name='send_detail'),
	url(r'^sends/(?P<sendid>\d+)/edit/$', views.edit_send, name='edit_send'),
	url(r'^sends/(?P<sendid>\d+)/delete/$', views.delete_send, name='delete_send'),
	url(r'^sends/(?P<sendid>\d+)/delete/confirm/$', views.delete_confirm, name='delete_confirm'),
	url(r'^climb_list/$', views.climb_list, name='climb_list'),
	url(r'^new_climb/$', views.new_climb, name='new_climb'),
	url(r'^log_climb/$', views.log_climb, name='log_climb'),
	url(r'^add_video/$', views.add_video, name='add_video'),
	url(r'^user_list/$', views.user_list, name='user_list'),
	url(r'^users/(?P<uid>\d+)/$', views.user_profile, name='user_profile'),
	url(r'^user_details/$', views.user_details, name='user_details'),
	url(r'^accounts/', include('django.contrib.auth.urls')),
	url(r'^user_details/edit/$', views.edit_details, name='edit_details'),
	url(r'^login/$', auth_views.login, name='login'),
	url(r'^registration/logout', views.logout_view, name='logout'),
	url(r'^directions/$', TemplateView.as_view(template_name='directions.html'), name='directions'),
	url(r'^stats/$', views.stats, name='stats'),
]

collection/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count, Q, Sum
from django.db.models.signals import post_save
from django.dispatch.dispatcher import receiver
from datetime import datetime, timedelta



class Climb(models.Model):
	GRADES = (
        (13, '8b'),
		(12, '8a+'),
		(11, '8a'),
		(10, '7c+'),
		(9, '7c'),
		(8, '7b+'),
		(7, '7b'),
		(6, '7a+'),
		(5, '7a'),
		(4, '6c+'),
		(3, '6c'),
		(2, '6b+'),
	)
	STARS = (
		(3, '3'),
		(2, '2'),
		(1, '1'),
		(0, '0'),
	)
	name = models.CharField(max_length=255, unique=True)
	grade = models.IntegerField(choices=GRADES)
	stars = models.IntegerField(choices=STARS, null=True)
	global_repeats = models.IntegerField(null=True, default=0)
	slug = models.SlugField(unique=True)
	date = models.DateTimeField(auto_now_add=True)
	canvas = models.BooleanField(default=False)
	users = models.ManyToManyField(User, through='collection.UserLog')
	def __str__(self):
		return '%s %s' % (self.name, self.get_grade_display())
		


	
class Video(models.Model):
	climb = models.ForeignKey(Climb, on_delete=models.CASCADE)
	url = models.CharField(max_length=9999)
	uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return "%s" % (self.climb)


class UserLog(models.Model):
	GRADES = (
        (13, '8b'),
		(12, '8a+'),
		(11, '8a'),
		(10, '7c+'),
		(9, '7c'),
		(8, '7b+'),
		(7, '7b'),
		(6, '7a+'),
		(5, '7a'),
		(4, '6c+'),
		(3, '6c'),
		(2, '6b+'),
	)
	STARS = (
		(3, '3'),
		(2, '2'),
		(1, '1'),
		(0, '0'),
	)
	ATTEMPTS = (
		('More than 3', 'More than 3'),
		('3rd Go', '3rd Go'),
		('2nd Go', '2nd Go'),
		('Flash', 'Flash'),
	)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	climb = models.ForeignKey(Climb, on_delete=models.CASCADE)
	attempts = models.CharField(max_length=255, choices=ATTEMPTS, blank=True)
	personal_grade = models.IntegerField(choices=GRADES, blank=True)
	stars = models.IntegerField(choices=STARS, blank=True)
	comments = models.TextField(blank=True)
	date = models.DateTimeField(blank=True)
	recommended = models.BooleanField(default=False)
	def __str__(self):
		return "%s %s" % (self.user, self.climb)
	

		
@receiver(post_save, sender=UserLog)
def update_sends(sender, **kwargs):
	if kwargs.get('created', False):
		for userdetailsupdate in UserDetails.objects.filter():
			userdetailsupdate.save()
			

	
class UserDetails(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	location = models.CharField(max_length=255, blank=True)
	height = models.CharField(max_length=255, blank=True)
	weight = models.CharField(max_length=255, blank=True)
	ape_index = models.CharField("Ape Index", max_length=255, blank=True)
	moonboardlocation = models.CharField("Moonboard Location", max_length=255, blank=True)
	
	
	
	
	
	
		


	
	

collection/forms.py
from django.forms import ModelForm
from collection.models import Climb, UserLog, Video, UserDetails, User
from django import forms
from django.utils.text import slugify



class NewClimb(forms.ModelForm):
	class Meta:
		model = Climb
		fields = ('name', 'grade')
	def save(self):
		instance = super(NewClimb, self).save(commit=False)
		instance.slug = slugify (instance.name)
		instance.save()
		
		return instance
		
class LogClimb(forms.ModelForm):
	class Meta:
		model = UserLog
		fields = ('climb', 'date', 'attempts', 'personal_grade', 'stars', 'recommended', 'comments')
	def __init__(self, *args, **kwargs):
		super(LogClimb, self).__init__(*args, **kwargs)   
		self.fields['climb'].queryset = Climb.objects.order_by('name')
		
class EditSend(ModelForm):
	class Meta:
		model = UserLog
		fields = ('climb', 'attempts', 'date', 'personal_grade', 'stars', 'recommended', 'comments')
		

class AddVideo(forms.ModelForm):
	class Meta:
		model = Video
		fields = ('climb', 'url',)
	def __init__(self, *args, **kwargs):
		super(AddVideo, self).__init__(*args, **kwargs)   
		self.fields['climb'].queryset = Climb.objects.order_by('name')	
		
class EditClimb(ModelForm):
	class Meta:
		model = Climb
		fields = ('name', 'grade', 'stars', 'global_repeats')
		
		
class EditUserDetails(ModelForm):
	class Meta:
		model = UserDetails
		fields = ('first_name', 'last_name', 'location', 'height', 'weight', 'ape_index', 'moonboardlocation')
		



		


		
		

collection/templates/sends/delete_send.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Edit Climb Details{% endblock title %}

{% block maincontent %}

<h2>Delete Send</h2>
<br>
<b>User:</b> {{ send.user.userdetails.first_name }} {{ send.user.userdetails.last_name }}<br>
<b>Climb:</b> {{ send.climb }}<br>
<b>Grade:</b> {{ send.get_personal_grade_display }}<br>
<b>Attempts:</b> {{ send.attempts }}<br>
<b>Stars:</b> {{ send.stars }}<br>
<b>Date:</b> {{ send.date|date:"n/j/y" }}<br>
<b>Comments:</b> {{ send.comments }}<br><br>

<h3> <b>Are you sure?</b></h3>
Click <a href="confirm/">here</a> to confirm delete of this send.




	
	
{% endblock %}

collection/templates/sends/edit_send.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Edit Climb Details{% endblock title %}

{% block maincontent %}

<script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>

<h2>Edit Climb Details</h2>
<a href="/sends/{{ send.id }}/delete">[Delete this send]</a>
<br><br>

<form method="POST" action="/sends/{{ send.id }}/edit/" class="" />
{% csrf_token %}
{{ form.non_field_errors }}
<table class="formtable">
	<tr>
		<td>
		<b>Climb:</b>
		</td>	
		<td>{{ form.climb }}
		</td>
		<td>
		{{ form.climb.errors }}
		</td>
	</tr>
	<tr>
		<td>
		<b>Date: </b>
		</td>
		<td>
		<input id="datepicker" name="date" type="text" required value={{ send.date|date:"m/j/y"  }}>
		</td>
		<td>
		{{ form.date.errors }}
		</td>
	</tr>
	<tr>
		<td>
		<b>Attempts:</b>
		</td>
		<td>
		{{ form.attempts }}
		</td>
		<td>
		{{ form.attempts.errors }}
		</td>
	</tr>
	<tr>
		<td>
		<b>Personal Grade:</b>
		</td>
		<td>{{ form.personal_grade }}
		</td>
		<td>
		{{ form.personal_grade.errors }}
		</td>
	</tr>
	<tr>
		<td>
		<b>Stars:</b>
		</td>
		<td>{{ form.stars }}
		</td>
		<td>
		{{ form.stars.errors }}
		</td>
		</tr>
	<tr>
		<td>
		<b>Recommended:</b>
		</td>
		<td>
		{{ form.recommended }}
		</td>
		<td>
		{{ form.recommended.errors }}
		</td>
	</tr>
	<tr>
		<td>
		<b>Comments: </b>
		</td>
		<td>{{ form.comments }}
		</td>
		<td>
		{{ form.comments.errors }}
		</td>
	</tr>
	<tr>
		<td><button type="submit">Save</button>
		</td>
	</tr>
</table>
</form>
<br><br>







	
	
{% endblock %}

collection/templates/sends/send_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ climb.name }}{% endblock title %}

{% block maincontent %}

{{ send.id }}
{{ send.climb.name }}





{% endblock %}